const footerLinks = {
    "Paywall management": [
        { label: "Paywall builder", href: "/paywall-builder" },
        { label: "Onboarding builder", href: "/onboarding-builder" },
        { label: "AI generator", href: "/ai-generator" },
        { label: "A/B testing", href: "/ab-testing" },
        { label: "Autopilot", href: "/autopilot" },
        { label: "Targeting", href: "/targeting" },
        { label: "Localization", href: "/localization" },
        { label: "Remote config", href: "/remote-config" },
    ],
    Infrastructure: [
        { label: "Subscription SDK", href: "/subscription-sdk" },
        { label: "Subscriber sync", href: "/subscriber-sync" },
        { label: "Fallback paywalls", href: "/fallback-paywalls" },
        { label: "Refund saver", href: "/refund-saver" },
        { label: "Integrations", href: "/integrations" },
    ],
    Roles: [
        { label: "For developers", href: "/for-developers" },
        { label: "For marketers", href: "/for-marketers" },
        { label: "For app owners", href: "/for-app-owners" },
    ],
    Stages: [
        { label: "Indie", href: "/indie" },
        { label: "Startups", href: "/startups" },
        { label: "Publishers", href: "/publishers" },
        { label: "Enterprise", href: "/enterprise" },
    ],
    Cases: [
        { label: "Integrate subscriptions", href: "/integrate-subscriptions" },
        { label: "Grow app revenue", href: "/grow-app-revenue" },
        { label: "Analyze performance", href: "/analyze-performance" },
        { label: "Read our cases", href: "/case-studies" },
    ],
    "Migrate from": [
        { label: "RevenueCat", href: "/migrate/revenuecat" },
        { label: "Purchasely", href: "/migrate/purchasely" },
        { label: "Qonversion", href: "/migrate/qonversion" },
        { label: "Superwall", href: "/migrate/superwall" },
    ],
    SDK: [
        { label: "iOS", href: "/sdk/ios" },
        { label: "Android", href: "/sdk/android" },
        { label: "React Native", href: "/sdk/react-native" },
        { label: "Flutter", href: "/sdk/flutter" },
        { label: "FlutterFlow", href: "/sdk/flutterflow" },
        { label: "Kotlin Multiplatform", href: "/sdk/kotlin-multiplatform" },
        { label: "Capacitor", href: "/sdk/capacitor" },
        { label: "Unity", href: "/sdk/unity" },
        { label: "Stripe", href: "/sdk/stripe" },
    ],
    Resources: [
        { label: "Blog", href: "/blog" },
        { label: "Ebooks", href: "/ebooks" },
        { label: "Podcast", href: "/podcast" },
        { label: "Webinars", href: "/webinars" },
        { label: "Events", href: "/events" },
        { label: "Glossary", href: "/glossary" },
        { label: "Documentation", href: "/docs" },
        { label: "Paywall library", href: "/paywall-library" },
        { label: "LTV prediction model", href: "/ltv-prediction-model" },
        { label: "Apple fiscal calendar", href: "/apple-fiscal-calendar" },
        { label: "Apple receipt checker", href: "/apple-receipt-checker" },
        { label: "Subscription calculator", href: "/subscription-calculator" },
        { label: "Refund saver calculator", href: "/refund-saver-calculator" },
        { label: "In-app subscription reports", href: "/subscription-reports" },
        { label: "Community", href: "/community" },
    ],
    Analytics: [
        { label: "Revenue analytics", href: "/revenue-analytics" },
        { label: "LTV analytics", href: "/ltv-analytics" },
        { label: "AI predictive analytics", href: "/ai-predictive-analytics" },
        { label: "Apple ads manager", href: "/apple-ads-manager" },
    ],
    Company: [
        { label: "About us", href: "/about" },
        { label: "Contact us", href: "/contact" },
        { label: "Careers", href: "/careers" },
        { label: "Terms", href: "/terms" },
        { label: "Privacy policy", href: "/privacy" },
        { label: "Data protection", href: "/data-protection" },
        { label: "System status", href: "/status" },
        { label: "SOC2 compliance", href: "/soc2" },
        { label: "Become a partner", href: "/partners" },
    ],
};

export { footerLinks };